version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/klferreira/valiant

    steps:
      - checkout
      - run:
          name: Run unit tests
          command: go test ./...